$ node example.js

node:internal/abort_controller:145
      throw this.reason;
      ^

DOMException [AbortError]: This operation was aborted
    at AbortController.abort (node:internal/abort_controller:319:18)
    at Object.<anonymous> (/whats-new-in-node-js-core/features/abort-api-abortsignal-throwifaborted/example.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
